### PR TITLE
League - getHistoricMatchesByLeagueAndSeason

### PR DESCRIPTION
**Pull request by ronierisson**
Was missing add the league in method . 

Congratulations on your beautiful API that you created.

### CODE REVIEW

**Comment by pabloo99** [comment]
Thanks.

**Comment by ronierisson** [comment]
You got to put the change in Maven?
Because I'm still the same error even updating the project dependency.
I believe that there has not yet been updated.

**Comment by pabloo99** [comment]
I just made deploy. Now you should be ok but I do not know how long it would be before the changes appear in the Maven repository.

**Comment by ronierisson** [comment]
All right. Today I do validation so get home to you through a position.
Thank U.

**Pull request merged**
